const {getProducts,money,getWhatsApp,toast,escape,getSite}=MM;
let activeCategory='Todos',searchTerm='',deferredPrompt=null;
const $=s=>document.querySelector(s),grid=$('#productGrid'),filters=$('#categoryFilters'),launchGrid=$('#launchGrid');
function site(){return getSite()} function label(c){return site().categories?.[c]?.label||c}
function visible(){return getProducts().filter(p=>p.active!==false)}
function imagesOf(p){const a=Array.isArray(p.images)?p.images.filter(Boolean):[];if(p.image&&!a.includes(p.image))a.unshift(p.image);return a.length?a:['sem-imagem.svg']}
function card(p){const out=Number(p.stock||0)<1;return `<article class="card product-card" data-open="${escape(p.id)}"><div class="image-wrap">${p.isLaunch?'<span class="launch-badge">Lançamento</span>':''}<img src="${escape(imagesOf(p)[0])}" alt="${escape(p.name)}" onerror="this.src='sem-imagem.svg'"></div><div class="card-body"><span class="chip">${escape(label(p.category))}</span><h3>${escape(p.name)}</h3><div class="price">${money(p.price)}</div><p class="availability ${out?'out':''}">${out?'Esgotado':'Disponível'}</p><div class="card-actions"><button class="btn secondary" data-details="${escape(p.id)}">Ver detalhes</button><button class="btn primary" data-whats="${escape(p.id)}" ${out?'disabled':''}>WhatsApp</button></div></div></article>`}
function bind(root=document){root.querySelectorAll('[data-details]').forEach(b=>b.onclick=e=>{e.stopPropagation();openProduct(b.dataset.details)});root.querySelectorAll('[data-whats]').forEach(b=>b.onclick=e=>{e.stopPropagation();sendProduct(b.dataset.whats)});root.querySelectorAll('[data-open]').forEach(c=>c.onclick=()=>openProduct(c.dataset.open))}
function renderSite(){const s=site();$('#heroTitle').textContent=s.heroTitle||'Margarida Maria';$('#heroText').textContent=s.heroText||'';$('#categorias').hidden=s.showCategories===false;$('#lancamentos').hidden=s.showLaunches===false;const cats=s.categories||{};$('#categoryPhotoGrid').innerHTML=['Cama','Mesa','Banho','Infantil'].map(c=>`<button class="category-photo-card" data-cat-photo="${c}"><img src="${escape(cats[c]?.image||'sem-imagem.svg')}" alt="${escape(cats[c]?.label||c)}"><span>${escape(cats[c]?.label||c)}</span></button>`).join('');document.querySelectorAll('[data-cat-photo]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.catPhoto;renderCatalog();$('#catalogo').scrollIntoView({behavior:'smooth'})})}
function renderCatalog(){const p=visible(),cats=['Todos',...new Set(p.map(x=>x.category))];filters.innerHTML=cats.map(c=>`<button class="btn ${activeCategory===c?'primary':'secondary'}" data-cat="${c}">${c==='Todos'?'Todos':escape(label(c))}</button>`).join('');filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;renderCatalog()});const q=searchTerm.toLocaleLowerCase('pt-BR');const list=p.filter(x=>(activeCategory==='Todos'||x.category===activeCategory)&&(!q||`${x.name} ${x.description||''}`.toLocaleLowerCase('pt-BR').includes(q)));grid.innerHTML=list.map(card).join('')||'<div class="empty-state">Nenhum produto encontrado.</div>';bind(grid)}
function renderLaunches(){const l=visible().filter(p=>p.isLaunch).slice(0,6);launchGrid.innerHTML=l.length?l.map(card).join(''):'<div class="empty-state">Os próximos lançamentos aparecerão aqui.</div>';bind(launchGrid)}
function sendProduct(id){const p=getProducts().find(x=>x.id===id);if(!p)return;const phone=getWhatsApp();const url=new URL(location.href);url.hash=`produto-${encodeURIComponent(id)}`;window.open(`https://wa.me/${phone}?text=${encodeURIComponent(`Olá! Tenho interesse em ${p.name} (${money(p.price)}).\n${url.href}`)}`,'_blank','noopener')}
function openProduct(id){const p=getProducts().find(x=>x.id===id);if(!p)return;const imgs=imagesOf(p),m=$('#productModal');$('#modalContent').innerHTML=`<div class="product-detail"><div class="product-gallery"><img class="product-main-image" id="productMainImage" src="${escape(imgs[0])}" alt="${escape(p.name)}"><div class="product-thumbs">${imgs.map((x,i)=>`<button class="product-thumb ${i===0?'active':''}" data-src="${escape(x)}"><img src="${escape(x)}"></button>`).join('')}</div><p class="zoom-help">🔍 Clique na foto para ampliar</p></div><div class="product-info"><span class="chip">${escape(label(p.category))}</span>${p.isLaunch?'<span class="launch-inline">Lançamento</span>':''}<h2>${escape(p.name)}</h2><div class="price big">${money(p.price)}</div><h3>Descrição</h3><p class="product-description">${escape(p.description||'Descrição não cadastrada.')}</p><p class="muted">${Number(p.stock||0)>0?`Disponível · ${Number(p.stock||0)} em estoque`:'Esgotado no momento'}</p><button class="btn primary" id="modalWhats" ${Number(p.stock||0)<1?'disabled':''}>Pedir no WhatsApp</button></div></div>`;$('#productMainImage').onclick=e=>openZoom(e.currentTarget.src);document.querySelectorAll('.product-thumb').forEach(b=>b.onclick=()=>{$('#productMainImage').src=b.dataset.src;document.querySelectorAll('.product-thumb').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$('#modalWhats').onclick=()=>sendProduct(id);m.classList.add('open');document.body.classList.add('modal-open')}
function closeModal(){$('#productModal').classList.remove('open');document.body.classList.remove('modal-open')} function openZoom(src){$('#zoomImage').src=src;$('#zoomViewer').classList.add('open')} function closeZoom(){$('#zoomViewer').classList.remove('open')}
$('#modalClose').onclick=closeModal;$('#productModal').onclick=e=>{if(e.target.id==='productModal')closeModal()};$('#zoomClose').onclick=closeZoom;$('#zoomViewer').onclick=e=>{if(e.target.id==='zoomViewer'||e.target.id==='zoomImage')closeZoom()};$('#searchInput').oninput=e=>{searchTerm=e.target.value;renderCatalog()};document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeZoom()}});
function installed(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true} function updateInstall(){const b=$('#installTop');if(installed()){b.hidden=true;return} if(deferredPrompt||/iPhone|iPad|iPod/.test(navigator.userAgent))b.hidden=false;else b.hidden=true}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;updateInstall()});window.addEventListener('appinstalled',()=>{deferredPrompt=null;updateInstall();toast('Aplicativo instalado!')});$('#installTop').onclick=async()=>{if(installed())return;if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;updateInstall()}else toast('No iPhone/iPad: Compartilhar → Adicionar à Tela de Início.')};
window.addEventListener('mm-products-changed',()=>{renderCatalog();renderLaunches()});window.addEventListener('mm-site-changed',()=>{renderSite();renderCatalog()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});renderSite();renderCatalog();renderLaunches();updateInstall();const h=decodeURIComponent(location.hash||'');if(h.startsWith('#produto-'))setTimeout(()=>openProduct(h.slice(9)),80);// Cadastro público de clientes - V5
(()=>{const f=document.getElementById('clientForm');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('clientName').value.trim(),phone=document.getElementById('clientPhone').value.trim(),email=document.getElementById('clientEmail').value.trim();if(!name)return;const users=JSON.parse(localStorage.getItem('mm_users')||'[]');users.push({name,phone,email,createdAt:new Date().toISOString(),source:'site'});localStorage.setItem('mm_users',JSON.stringify(users));f.reset();MM.toast('Cadastro realizado! Você receberá nossas novidades.');});})();
