-- Margarida Maria — Histórias da Maria
-- Execute UMA VEZ no Supabase > SQL Editor.

create table if not exists public.historias_maria (
  id bigint generated by default as identity primary key,
  titulo text not null,
  cliente_nome text default '',
  situacao text default '',
  fala_cliente text default '',
  fala_maria text default '',
  imagem text default '',
  produto_ids jsonb not null default '[]'::jsonb,
  publicada boolean not null default false,
  ordem integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.historias_maria enable row level security;

drop policy if exists "publico_le_historias_publicadas" on public.historias_maria;
create policy "publico_le_historias_publicadas"
on public.historias_maria for select
to anon, authenticated
using (publicada = true or (auth.jwt() ->> 'email') = 'margaridamaria9530@gmail.com');

drop policy if exists "admin_cria_historias" on public.historias_maria;
create policy "admin_cria_historias"
on public.historias_maria for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'margaridamaria9530@gmail.com');

drop policy if exists "admin_atualiza_historias" on public.historias_maria;
create policy "admin_atualiza_historias"
on public.historias_maria for update
to authenticated
using ((auth.jwt() ->> 'email') = 'margaridamaria9530@gmail.com')
with check ((auth.jwt() ->> 'email') = 'margaridamaria9530@gmail.com');

drop policy if exists "admin_exclui_historias" on public.historias_maria;
create policy "admin_exclui_historias"
on public.historias_maria for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'margaridamaria9530@gmail.com');

grant select on public.historias_maria to anon, authenticated;
grant insert, update, delete on public.historias_maria to authenticated;
